project:
  type: book

book:
  title: "실험계획법 2024 강의 노트"
  author: "서울시립대학교 통계힉과 이용희"
  date: last-modified
  downloads: [pdf]
  chapters:
    - index.qmd
    - qmd/oneway.qmd
    - qmd/twoway.qmd
    - qmd/block.qmd
    - qmd/contrast.qmd
    - qmd/twolevels.qmd
    - qmd/twolevelscomf.qmd
    - qmd/response.qmd
    - references.qmd
  appendices:    
    - qmd/visual.qmd
    - qmd/linear.qmd
    - qmd/raneff.qmd
    - qmd/comfound.qmd

  
bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    lang: ko
    language: custom.yml
    code-fold: false
    code-overflow: wrap
    embed-resources: false
    citations-hover: true
    footnotes-hover: true
    crossref:
      fig-prefix: 그림   # (default is "Figure")
      tbl-prefix: 표    # (default is "Table")
      eq-prefix: 식     # (default is "Equation")
      ref-hyperlink: true # (default is true)
    include-in-header:
      - text: |
          <script type="text/javascript">
           window.MathJax = {
            tex: {
              macros: {
              RR: '{\\mathbb R}',                    // a simple string replacement
              hatmat:'{\\pmb X ({\\pmb X}^t {\\pmb X} )^{-1} {\\pmb X}^t}',
              bold: ['\\boldsymbol{#1}',1] ,     // this macro has one parameter
              pardiff: ['\\frac{\\partial#2}{\\partial#1}', 2, 'x'], // this macro has an optional parameter that defaults to 'x'
              pardifftwo: ['\\frac{\\partial#1}{\\partial#2}', 2]
            },
            environments: {
            braced: ["\\left\\{", "\\right\\}"]
            }
           }
          };
          </script>
#    include-before-body:
#      - latex/preamble-mathjax.tex
  # bookup-html:
  #   toc: true
  #   toc-depth: 2
  #   language: custom.yml
  #   code-fold: true
  #   code-overflow: wrap
  #   embed-resources: true
  #   include-in-header:
  #     - latex/preamble-mathjax.tex
  # 
  pdf:
    documentclass: scrbook
    classoption: oneside
    papersize: A4
    lang: ko
    language: custom.yml
    fontsize: 10pt
    lof: false
    lot: false
    code-overflow: wrap
    latex-auto-install: true
    latex-tinytex: true
    pdf-engine: xelatex
    crossref:
      fig-prefix: 그림   # (default is "Figure")
      tbl-prefix: 표    # (default is "Table")
      eq-prefix: 식     # (default is "Equation")
      ref-hyperlink: true # (default is true)
    include-in-header: latex/preamble.tex


